"""Packs gen_cg.mjs output into ../HeyTattvaCG/assets.h (4-bit RLE masks, zlib) and the two music beds into
../HeyTattvaCG/beds.h (IMA-ADPCM, 16 kHz mono). Usage: python3 pack_cg.py BED1.pcm BED4.pcm"""
import json,os,sys,zlib,struct
from PIL import Image
import qrcode
H=os.path.dirname(os.path.abspath(__file__));OUT=os.path.join(H,'out');DST=os.path.join(H,'..','HeyTattvaCG')
M=json.load(open(os.path.join(OUT,'manifest.json')))
data=bytearray();blocks=[];items={}
def rle(px):
    out=bytearray();i=0;n=len(px)
    while i<n:
        if px[i]==0:
            j=i
            while j<n and px[j]==0 and j-i<128:j+=1
            out.append(0x80|(j-i-1));i=j
        elif px[i]==15:
            j=i
            while j<n and px[j]==15 and j-i<64:j+=1
            out.append(0x40|(j-i-1));i=j
        else:
            j=i
            while j<n and j-i<64 and px[j] not in (0,15):j+=1
            seg=px[i:j];out.append(len(seg)-1)
            for k in range(0,len(seg),2):out.append((seg[k]<<4)|(seg[k+1] if k+1<len(seg) else 0))
            i=j
    return out
for m in M['man']:
    first=len(blocks);W=H2=0
    for L in m['layers']:
        im=Image.open(os.path.join(OUT,L['file'])).convert('RGBA');a=im.split()[3];W,H2=im.size;bb=a.getbbox()
        if not bb:continue
        c=a.crop(bb);w,h=c.size;px=[(v*15+127)//255 for v in c.getdata()]
        off=len(data);data.extend(rle(px));blocks.append((bb[0],bb[1],w,h,255,off))
    items[m['id']]=(first,len(blocks)-first,W,H2,int(round(m.get('adv',0))))
names=list(items);idx={k:i for i,k in enumerate(names)};I=lambda k:idx[k]
TT=M['TT'];o=['// Generated by device/cgotchi/tools/pack_cg.py. Do not edit.\n#pragma once\n#include <stdint.h>\n',
 'struct Blk{uint16_t x,y,w,h;uint8_t col;uint32_t off;};\nstruct Item{uint16_t first;uint8_t n;uint16_t w,h;int16_t adv;};\n']
z=zlib.compress(bytes(data),9)
o.append('#define ADATA_LEN %d\n#define ADATA_ZLEN %d\nstatic const uint8_t ADATA_Z[] = {%s};\nstatic uint8_t *ADATA = nullptr;\n'%(len(data),len(z),','.join(map(str,z))))
o.append('static const Blk BLK[] = {'+','.join('{%d,%d,%d,%d,%d,%d}'%b for b in blocks)+'};\n')
o.append('static const Item ITEMS[] = {'+','.join('{%d,%d,%d,%d,%d}'%items[k] for k in names)+'};\n')
o.append('#define NT 2\nstatic const uint8_t TTN[NT] = {%s};\n'%','.join(map(str,TT)))
for tag,key in [('LD','LD'),('LI','LI'),('LM','LM')]:o.append('static const uint16_t %s[NT][4] = {%s};\n'%(tag,','.join('{'+','.join(str(I('%s_%d_%d'%(key,n,k))) for k in range(4))+'}' for n in TT)))
o.append('static const uint16_t TEACH[NT] = {%s};\nstatic const uint16_t SYMI[NT] = {%s};\n'%(','.join(str(I('TEACH_%d'%n)) for n in TT),','.join(str(I('SYM_%d'%n)) for n in TT)))
o.append('static const char *TNAME[NT] = {%s};\n'%','.join(json.dumps(x['name']) for x in M['T']))
o.append('#define IT_YANTRA %d\n#define IT_BRAND_DEV %d\n'%(I('YANTRA'),I('BRAND_DEV')))
icons=[k[2:] for k in names if k.startswith('I_')]
o.append('enum Icon {'+','.join('IC_'+k.upper() for k in icons)+'};\nstatic const uint16_t ICON[] = {'+','.join(str(I('I_'+k)) for k in icons)+'};\n')
for tag in ['F14','F18','F26']:o.append('static const uint16_t G%s[95] = {%s};\n'%(tag,','.join(str(I('G_%s_%d'%(tag,c))) for c in range(32,127))))
o.append('static const char G48CH[] = "0123456789:%%/ ";\nstatic const uint16_t GF48[14] = {%s};\n'%','.join(str(I('G_F48_%d'%ord(c))) for c in '0123456789:%/ '))
o.append('static const uint16_t AKI[] = {%s};\n'%','.join(str(I('K_%d'%i)) for i in range(len(M['ak']))))
o.append('struct Word{uint8_t n;uint8_t ak[6];uint8_t key;uint16_t wd,wm;};\n')
for t in M['W']:
    rows=[]
    for j,w in enumerate(t['words']):
        a=[M['ak'].index(x) for x in w['ak']]+[0]*(6-len(w['ak']))
        rows.append('{%d,{%s},%d,%d,%d}'%(len(w['ak']),','.join(map(str,a)),1 if w['key'] else 0,I('WD_%d_%d'%(t['n'],j)),I('WM_%d_%d'%(t['n'],j))))
    o.append('static const Word WORDS%d[] = {%s};\n'%(t['n'],','.join(rows)))
o.append('static const Word *WORDS[NT] = {%s};\nstatic const uint8_t NWORDS[NT] = {%s};\n'%(','.join('WORDS%d'%n for n in TT),','.join(str(len(t['words'])) for t in M['W'])))
def qr(name,text):
    q=qrcode.QRCode(border=0,error_correction=qrcode.constants.ERROR_CORRECT_M);q.add_data(text);q.make(fit=True);mt=q.get_matrix();n=len(mt)
    bits=bytearray((n*n+7)//8)
    for y in range(n):
        for x in range(n):
            if mt[y][x]:i=y*n+x;bits[i>>3]|=1<<(i&7)
    o.append('static const uint8_t %s_BITS[] = {%s};\nstatic const uint8_t %s_N = %d;\n'%(name,','.join(map(str,bits)),name,n))
qr('QR_WIFI','WIFI:T:nopass;S:HeyTattva-Setup;;');qr('QR_SITE','https://heytattva.vercel.app')
open(os.path.join(DST,'assets.h'),'w').write(''.join(o))
print('masks',len(blocks),'items',len(items),'data',len(data),'zip',len(z))
# ---- music beds: IMA-ADPCM ----
STEP=[7,8,9,10,11,12,13,14,16,17,19,21,23,25,28,31,34,37,41,45,50,55,60,66,73,80,88,97,107,118,130,143,157,173,190,209,230,253,279,307,337,371,408,449,494,544,598,658,724,796,876,963,1060,1166,1282,1411,1552,1707,1878,2066,2272,2499,2749,3024,3327,3660,4026,4428,4871,5358,5894,6484,7132,7845,8630,9493,10442,11487,12635,13899,15289,16818,18500,20350,22385,24623,27086,29794,32767]
IDX=[-1,-1,-1,-1,2,4,6,8,-1,-1,-1,-1,2,4,6,8]
def enc(samples):
    pred=0;ix=0;out=bytearray();dec=[];nib=[]
    for s in samples:
        st=STEP[ix];d=s-pred;code=0
        if d<0:code=8;d=-d
        diff=st>>3
        if d>=st:code|=4;d-=st;diff+=st
        if d>=st>>1:code|=2;d-=st>>1;diff+=st>>1
        if d>=st>>2:code|=1;diff+=st>>2
        pred=pred-diff if code&8 else pred+diff;pred=max(-32768,min(32767,pred))
        ix=max(0,min(88,ix+IDX[code]));nib.append(code);dec.append(pred)
    if len(nib)%2:nib.append(0)
    for k in range(0,len(nib),2):out.append(nib[k]|(nib[k+1]<<4))
    return out,dec
b=['// Generated by pack_cg.py: the two music beds (sitar, tanpura, tabla), IMA-ADPCM 16 kHz mono.\n#pragma once\n#include <stdint.h>\n']
for k,f in enumerate(sys.argv[1:3]):
    raw=open(f,'rb').read();s=list(struct.unpack('<%dh'%(len(raw)//2),raw))
    e,dec=enc(s);sig=sum(x*x for x in s)/len(s);err=sum((x-y)**2 for x,y in zip(s,dec))/len(s)
    import math;print('bed',k,'samples',len(s),'bytes',len(e),'SNR %.1f dB'%(10*math.log10(sig/max(err,1))))
    b.append('static const uint32_t BED%d_N = %d;\nstatic const uint8_t BED%d[] = {%s};\n'%(k,len(s),k,','.join(map(str,e))))
open(os.path.join(DST,'beds.h'),'w').write(''.join(b))
