"""Packs the rendered layers (out/manifest.json) into ../HeyTattva/assets.h: 4-bit alpha masks, run-length coded,
plus index tables, the Sing tunes and three QR codes."""
import json,os,re
from PIL import Image
import qrcode,zlib
H=os.path.dirname(os.path.abspath(__file__));OUT=os.path.join(H,'out');DST=os.path.join(H,'..','HeyTattva','assets.h')
M=json.load(open(os.path.join(OUT,'manifest.json')))
COL={'gold':0,'ink':1,'muted':2,'w':255}
data=bytearray();blocks=[];items={}
def rle(px):
    out=bytearray();i=0;n=len(px)
    while i<n:
        if px[i]==0:
            j=i
            while j<n and px[j]==0 and j-i<128:j+=1
            out.append(0x80|(j-i-1));i=j
        elif px[i]==15:
            j=i
            while j<n and px[j]==15 and j-i<64:j+=1
            out.append(0x40|(j-i-1));i=j
        else:
            j=i
            while j<n and j-i<64 and px[j] not in (0,15):j+=1
            if j==i:j=i+1
            seg=px[i:j];out.append(len(seg)-1)
            for k in range(0,len(seg),2):out.append((seg[k]<<4)|(seg[k+1] if k+1<len(seg) else 0))
            i=j
    return out
for m in M['man']:
    first=len(blocks);W=H2=0
    for L in m['layers']:
        im=Image.open(os.path.join(OUT,L['file'])).convert('RGBA');a=im.split()[3]
        W,H2=im.size;bb=a.getbbox()
        if not bb:continue
        c=a.crop(bb);w,h=c.size;px=[(v*15+127)//255 for v in c.getdata()]
        off=len(data);data.extend(rle(px));blocks.append((bb[0],bb[1],w,h,COL[L['color']],off))
    items[m['id']]=(first,len(blocks)-first,W,H2,int(round(m.get('adv',0))))
names=list(items.keys());idx={k:i for i,k in enumerate(names)}
def I(k):return idx[k]
L=['en','te','kn','hi'];keys=M['keys']
def cname(k):
    s=re.sub(r'[^A-Za-z0-9]+','_',k).strip('_').upper();return 'S_'+s[:40]
o=[]
o.append('// Generated by device/tools/pack.py from the website text. Do not edit by hand.\n#pragma once\n#include <stdint.h>\n')
o.append('struct Blk{uint16_t x,y,w,h;uint8_t col;uint32_t off;};\nstruct Item{uint16_t first;uint8_t n;uint16_t w,h;int16_t adv;};\n')
z=zlib.compress(bytes(data),9)
o.append('// the masks, zlib-compressed; unpacked into PSRAM at start-up (ROM inflate on the ESP32)\n#define ADATA_LEN %d\n#define ADATA_ZLEN %d\nstatic const uint8_t ADATA_Z[] = {'%(len(data),len(z))+','.join(str(b) for b in z)+'};\nstatic uint8_t *ADATA = nullptr;\n')
o.append('static const Blk BLK[] = {'+','.join('{%d,%d,%d,%d,%d,%d}'%b for b in blocks)+'};\n')
o.append('static const Item ITEMS[] = {'+','.join('{%d,%d,%d,%d,%d}'%items[k] for k in names)+'};\n')
o.append('static const uint16_t PAGE[4][8][3] = {'+','.join('{'+','.join('{'+','.join(str(I('P_%s_%d_%s'%(l,n,k))) for k in 'VMK')+'}' for n in range(1,9))+'}' for l in L)+'};\n')
o.append('enum StrKey {'+','.join(cname(k) for k in keys)+',S_COUNT};\n')
o.append('static const uint16_t STR[4][%d] = {'%len(keys)+','.join('{'+','.join(str(I('S_%s_%d'%(l,i))) for i in range(len(keys)))+'}' for l in L)+'};\n')
o.append('static const uint16_t LANGN[4] = {'+','.join(str(I('LANG_%d'%i)) for i in range(4))+'};\n')
for k in ['BRAND','BRAND_DEV','BRAND_SUB','OM','YANTRA']:o.append('#define IT_%s %d\n'%(k,I(k)))
o.append('static const uint16_t SYM[9] = {0,'+','.join(str(I('SYM_%d'%n)) for n in range(1,9))+'};\n')
icons=[k[2:] for k in names if k.startswith('I_')]
o.append('enum Icon {'+','.join('IC_'+k.upper() for k in icons)+'};\nstatic const uint16_t ICON[] = {'+','.join(str(I('I_'+k)) for k in icons)+'};\n')
for tag in ['A16','A24']:o.append('static const uint16_t G%s[95] = {'%tag+','.join(str(I('G_%s_%d'%(tag,c))) for c in range(32,127))+'};\n')
o.append('static const uint16_t GD64[12] = {'+','.join(str(I('G_D64_%d'%ord(c))) for c in '0123456789:%')+'};\n')
o.append('static const uint16_t SYLI[] = {'+','.join(str(I('Y_%d'%i)) for i in range(len(M['syl'])))+'};\n')
# tunes: semitone, start (quarter beats), length (quarter beats), syllable
o.append('struct Note{int8_t semi;uint16_t start;uint16_t len;uint16_t syl;};\nstruct Tune{uint16_t bpm;uint16_t total4;uint16_t n;const Note*notes;};\n')
for v in range(1,9):
    t=M['tunes'][str(v)]
    o.append('static const Note TN%d[] = {'%v+','.join('{%d,%d,%d,%d}'%(x[0],round(x[1]*4),round(x[2]*4),M['syl'].index(x[3])) for x in t['n'])+'};\n')
o.append('static const Tune TUNE[9] = {{0,0,0,0},'+','.join('{%d,%d,%d,TN%d}'%(M['tunes'][str(v)]['bpm'],round(M['tunes'][str(v)]['total']*4),len(M['tunes'][str(v)]['n']),v) for v in range(1,9))+'};\n')
def qr(name,text):
    q=qrcode.QRCode(border=0,error_correction=qrcode.constants.ERROR_CORRECT_M);q.add_data(text);q.make(fit=True);mt=q.get_matrix();n=len(mt)
    bits=bytearray((n*n+7)//8)
    for y in range(n):
        for x in range(n):
            if mt[y][x]:i=y*n+x;bits[i>>3]|=1<<(i&7)
    o.append('static const uint8_t %s_BITS[] = {%s};\nstatic const uint8_t %s_N = %d;\n'%(name,','.join(map(str,bits)),name,n))
qr('QR_WIFI','WIFI:T:nopass;S:HeyTattva-Setup;;')
qr('QR_PORTAL','http://192.168.4.1')
qr('QR_SITE','https://heytattva.vercel.app')
open(DST,'w').write(''.join(o))
print('masks',len(blocks),'items',len(items),'data',len(data),'bytes; header',os.path.getsize(DST))
