/* The eight tattvas of the Dakṣiṇāmūrti Aṣṭakam (verses 1–8). Line 4 is the same refrain in every verse. */
const L4={dev:'तस्मै श्रीगुरुमूर्तये नम इदं श्रीदक्षिणामूर्तये ॥',iast:'tasmai śrī-guru-mūrtaye nama idaṁ śrī-dakṣiṇāmūrtaye',en:'to that Guru in form, Śrī Dakṣiṇāmūrti, I offer this salutation.'};
const TATTVAS=[
{n:1,name:'The mirror city',
 dev:['विश्वं दर्पणदृश्यमाननगरीतुल्यं निजान्तर्गतं','पश्यन्नात्मनि मायया बहिरिवोद्भूतं यथा निद्रया ।','यः साक्षात्कुरुते प्रबोधसमये स्वात्मानमेवाद्वयं'],
 iast:['viśvaṁ darpaṇa-dṛśyamāna-nagarī-tulyaṁ nijāntargataṁ','paśyann ātmani māyayā bahir ivodbhūtaṁ yathā nidrayā','yaḥ sākṣāt kurute prabodha-samaye svātmānam evādvayaṁ'],
 en:['The universe is like a city seen in a mirror. It exists within oneself.','Through māyā it seems to appear outside, as a dream does in sleep.','The one who, at the moment of awakening, sees directly his own Self, one without a second,'],
 teach:'The world you see is like a city reflected in a mirror. It seems to be outside, yet it shines within you.',
 keep:['A reflection depends on the mirror. The world you see depends on the awareness that sees it.','A dream city feels real until you wake. Then you see it was in you all along.','The guru’s gift is that awakening: you are the one awareness, without a second.'],
 words:[['viśvam','the universe'],['darpaṇa','mirror'],['dṛśyamāna','being seen'],['nagarī','city'],['tulyam','just like'],['nija-antargatam','within oneself'],['māyayā','through māyā'],['bahiḥ iva','as if outside'],['nidrayā','in sleep'],['prabodha-samaye','at awakening'],['sva-ātmānam','one’s own Self'],['advayam','without a second']]},
{n:2,name:'The seed',
 dev:['बीजस्यान्तरिवाङ्कुरो जगदिदं प्राङ्निर्विकल्पं पुनः','मायाकल्पितदेशकालकलनावैचित्र्यचित्रीकृतम् ।','मायावीव विजृम्भयत्यपि महायोगीव यः स्वेच्छया'],
 iast:['bījasyāntar ivāṅkuro jagad idaṁ prāṅ nirvikalpaṁ punaḥ','māyā-kalpita-deśa-kāla-kalanā-vaicitrya-citrīkṛtam','māyāvīva vijṛmbhayaty api mahā-yogīva yaḥ svecchayā'],
 en:['Like the sprout inside a seed, this world at first lies undivided.','Then, through māyā, it is painted with the endless variety of space and time.','The one who unfolds it by his own will, like a magician, like a great yogi,'],
 teach:'The whole world rests in the Self like a tree inside a seed. Space and time unfold it, the way a magician conjures a show.',
 keep:['A seed holds the whole tree before it sprouts. The Self holds the world before it appears.','Space and time are the painter’s brush: they give the one canvas its many colours.','Like a magician who is never fooled by his own show, the Self stays untouched by the world it unfolds.'],
 words:[['bījasya antaḥ','inside the seed'],['aṅkuraḥ','sprout'],['jagat idam','this world'],['prāk','at first'],['nirvikalpam','undivided'],['māyā-kalpita','imagined by māyā'],['deśa','space'],['kāla','time'],['vaicitrya','variety'],['citrīkṛtam','painted'],['māyāvī','magician'],['vijṛmbhayati','unfolds'],['mahā-yogī','great yogi'],['sva-icchayā','by his own will']]},
{n:3,name:'That you are',
 dev:['यस्यैव स्फुरणं सदात्मकमसत्कल्पार्थकं भासते','साक्षात्तत्त्वमसीति वेदवचसा यो बोधयत्याश्रितान् ।','यत्साक्षात्करणाद्भवेन्न पुनरावृत्तिर्भवाम्भोनिधौ'],
 iast:['yasyaiva sphuraṇaṁ sadātmakam asat-kalpārthakaṁ bhāsate','sākṣāt tat tvam asīti veda-vacasā yo bodhayaty āśritān','yat-sākṣāt-karaṇād bhaven na punar āvṛttir bhavāmbhonidhau'],
 en:['His shining alone, which is existence itself, appears in things that are unreal.','Through the Vedic words “You are That”, he awakens those who come to him.','Seeing That directly, one never returns to the ocean of birth and death,'],
 teach:'Everything you see shines only because existence shines through it. The guru points and says: you are That.',
 keep:['A pot “is”, a tree “is”. That “is” is the one existence shining in every thing.','“Tat tvam asi”: what shines in everything is what you are.','Know it directly, and the cycle of becoming has nowhere to pull you back.'],
 words:[['sphuraṇam','shining'],['sat-ātmakam','existence itself'],['asat','unreal'],['bhāsate','appears'],['sākṣāt','directly'],['tat','That'],['tvam','you'],['asi','are'],['veda-vacasā','by the words of the Veda'],['bodhayati','awakens'],['āśritān','those who come'],['āvṛttiḥ','return'],['bhava-ambhonidhau','in the ocean of becoming']]},
{n:4,name:'The lamp in the pot',
 dev:['नानाच्छिद्रघटोदरस्थितमहादीपप्रभाभास्वरं','ज्ञानं यस्य तु चक्षुरादिकरणद्वारा बहिः स्पन्दते ।','जानामीति तमेव भान्तमनुभात्येतत्समस्तं जगत्'],
 iast:['nānācchidra-ghaṭodara-sthita-mahā-dīpa-prabhā-bhāsvaraṁ','jñānaṁ yasya tu cakṣur-ādi-karaṇa-dvārā bahiḥ spandate','jānāmīti tam eva bhāntam anubhāty etat samastaṁ jagat'],
 en:['Like the bright light of a great lamp inside a pot with many holes,','his knowing streams outward through the eyes and the other senses.','“I know”: he shines, and only after him does this whole world shine,'],
 teach:'Your awareness is a lamp inside a pot full of holes. It shines out through the eyes and ears, and the world lights up.',
 keep:['The holes are many, the light is one. The senses are many, awareness is one.','Nothing in the world shines by itself. It is seen because awareness shines first.','“I know” is the lamp. Everything known is lit by it.'],
 words:[['nānā chidra','many holes'],['ghaṭa-udara','inside a pot'],['mahā-dīpa','great lamp'],['prabhā','light'],['jñānam','knowing'],['cakṣuḥ-ādi','the eyes and the rest'],['karaṇa','senses'],['dvārā','through'],['bahiḥ','outward'],['spandate','streams'],['jānāmi','I know'],['bhāntam','shining'],['anubhāti','shines after']]},
{n:5,name:'Not the body',
 dev:['देहं प्राणमपीन्द्रियाण्यपि चलां बुद्धिं च शून्यं विदुः','स्त्रीबालान्धजडोपमास्त्वहमिति भ्रान्ता भृशं वादिनः ।','मायाशक्तिविलासकल्पितमहाव्यामोहसंहारिणे'],
 iast:['dehaṁ prāṇam apīndriyāṇy api calāṁ buddhiṁ ca śūnyaṁ viduḥ','strī-bālāndha-jaḍopamās tv aham iti bhrāntā bhṛśaṁ vādinaḥ','māyā-śakti-vilāsa-kalpita-mahā-vyāmoha-saṁhāriṇe'],
 en:['Some take the “I” to be the body, the breath, the senses, the restless mind, or emptiness.','Naive as children or the blind, they are deeply mistaken, though they argue loudly.','To him who ends this great delusion, conjured by the play of māyā’s power,'],
 teach:'You are not the body, the breath, the senses or the mind. Those are things you know. The knower is what you are.',
 keep:['Whatever you can watch is not the watcher. You watch the body, the breath, the thoughts.','Thoughts come and go. The one who sees them come and go stays.','The guru doesn’t add anything. He removes the mistake, and what is left is you.'],
 words:[['deham','body'],['prāṇam','breath'],['indriyāṇi','senses'],['calām buddhim','restless mind'],['śūnyam','emptiness'],['viduḥ','they take to be'],['aham iti','as “I”'],['bhrāntāḥ','mistaken'],['vādinaḥ','debaters'],['māyā-śakti','power of māyā'],['vilāsa','play'],['vyāmoha','delusion'],['saṁhāriṇe','to the one who ends']]},
{n:6,name:'The eclipse',
 dev:['राहुग्रस्तदिवाकरेन्दुसदृशो मायासमाच्छादनात्','सन्मात्रः करणोपसंहरणतो योऽभूत्सुषुप्तः पुमान् ।','प्रागस्वाप्समिति प्रबोधसमये यः प्रत्यभिज्ञायते'],
 iast:['rāhu-grasta-divākarendu-sadṛśo māyā-samācchādanāt','san-mātraḥ karaṇopasaṁharaṇato yo ’bhūt suṣuptaḥ pumān','prāg asvāpsam iti prabodha-samaye yaḥ pratyabhijñāyate'],
 en:['Like the sun or the moon swallowed by Rāhu, covered over by māyā,','the one who in deep sleep, with the senses withdrawn, remains as pure existence,','on waking recognises himself: “I was asleep”,'],
 teach:'In deep sleep you seem to vanish, like an eclipsed sun. On waking you say “I slept well”, so you were there all along.',
 keep:['An eclipse hides the sun from us. The sun itself is never touched.','In deep sleep the senses and the mind fold away, but you remain as pure being.','“I slept well” is a memory. Someone was there to have it.'],
 words:[['rāhu-grasta','seized by Rāhu'],['divākara','sun'],['indu','moon'],['sadṛśaḥ','like'],['samācchādanāt','by covering'],['sat-mātraḥ','pure existence'],['karaṇa','senses'],['upasaṁharaṇataḥ','by withdrawing'],['suṣuptaḥ','deeply asleep'],['pumān','person'],['prāk asvāpsam','“I slept until now”'],['prabodha-samaye','on waking'],['pratyabhijñāyate','recognises himself']]},
{n:7,name:'The unchanging I',
 dev:['बाल्यादिष्वपि जाग्रदादिषु तथा सर्वास्ववस्थास्वपि','व्यावृत्तास्वनुवर्तमानमहमित्यन्तः स्फुरन्तं सदा ।','स्वात्मानं प्रकटीकरोति भजतां यो मुद्रया भद्रया'],
 iast:['bālyādiṣv api jāgrad-ādiṣu tathā sarvāsv avasthāsv api','vyāvṛttāsv anuvartamānam aham ity antaḥ sphurantaṁ sadā','svātmānaṁ prakaṭīkaroti bhajatāṁ yo mudrayā bhadrayā'],
 en:['In childhood, youth and age, in waking, dream and deep sleep, in every state,','while the states come and go, the “I am” continues, always shining within.','He reveals this, one’s own Self, to those who seek him, with the auspicious gesture of knowledge,'],
 teach:'Childhood ends, youth ends, dreams end. The “I am” that was present in all of them never ends.',
 keep:['The states change like beads. The thread of “I am” runs through all of them.','You were a child and you are older now. The “I” that says both is the same.','The chin-mudrā: the finger of the self touches the thumb of the infinite, and the circle closes.'],
 words:[['bālya-ādiṣu','in childhood and the rest'],['jāgrat-ādiṣu','in waking and the rest'],['avasthāsu','in the states'],['vyāvṛttāsu','as they pass'],['anuvartamānam','continuing'],['aham iti','as “I”'],['antaḥ','within'],['sphurantam','shining'],['sadā','always'],['sva-ātmānam','one’s own Self'],['prakaṭīkaroti','reveals'],['bhajatām','to those who seek'],['mudrayā bhadrayā','with the auspicious gesture']]},
{n:8,name:'The dream of roles',
 dev:['विश्वं पश्यति कार्यकारणतया स्वस्वामिसंबन्धतः','शिष्याचार्यतया तथैव पितृपुत्राद्यात्मना भेदतः ।','स्वप्ने जाग्रति वा य एष पुरुषो मायापरिभ्रामितः'],
 iast:['viśvaṁ paśyati kārya-kāraṇatayā sva-svāmi-saṁbandhataḥ','śiṣyācāryatayā tathaiva pitṛ-putrādy-ātmanā bhedataḥ','svapne jāgrati vā ya eṣa puruṣo māyā-paribhrāmitaḥ'],
 en:['One sees the world as cause and effect, as the owned and the owner,','as student and teacher, as father and son, all as division.','In dream or in waking, this person is spun around by māyā,'],
 teach:'Cause and effect, owner and owned, teacher and student, parent and child. One Self plays every role, like a dreamer who is every person in the dream.',
 keep:['In a dream you are the city, the crowd and the one walking through it.','Roles are real as roles. The one playing them is not divided.','The guru wakes you, the way morning ends a dream.'],
 words:[['viśvam','the world'],['paśyati','sees'],['kārya','effect'],['kāraṇa','cause'],['sva','the owned'],['svāmi','owner'],['saṁbandhataḥ','through relation'],['śiṣya','student'],['ācārya','teacher'],['pitṛ','father'],['putra','son'],['bhedataḥ','as division'],['svapne','in dream'],['jāgrati','in waking'],['māyā-paribhrāmitaḥ','spun by māyā']]}
];
TATTVAS.forEach(t=>{t.dev.push(L4.dev);t.iast.push(L4.iast);t.en.push(L4.en);t.words.push(['namaḥ','salutations']);});
